develop - added functionality according to the terms of reference and tests
marussiakuz/java-explore-with-me pull request #1
Opened 2022-10-05 21:31 UTC by marussiakuz

2022-10-06 16:39 UTC, damirovna requested changes
Потрясающая работа! 

Очень сложно было найти к чему придраться.

2022-10-06 16:39 UTC, damirovna commented on main-server/src/main/resources/schema.sql
> +    category_name VARCHAR UNIQUE NOT NULL,
[Нужно исправить]

Пожалуйста, ограничьте размер VARCHAR полей, при задании ограничения на размер email пользователя стоит учесть, что максимальная длина адреса прописана в https://www.rfc-editor.org/rfc/rfc5321#section-4.5.3

2022-10-06 16:39 UTC, damirovna commented on main-server/src/main/java/ru/practicum/ewm/event/model/dto/EventFullOutDto.java
> +public class EventFullOutDto implements EventOutDto {
[На подумать]

Можно ли как-то сократить количество кода, если учитывать, что класс EventFullOutDto содержит часть полей описанных в EventShortOutDto?

2022-10-06 16:39 UTC, damirovna commented on main-server/src/main/resources/schema.sql
> +    status VARCHAR(9) NOT NULL DEFAULT 'PENDING',
[Можно лучше]

Мне кажется, что в какой-то момент может понадобится создать для события ещё один статус, более длинный, чем 9 символов)))

2022-10-06 16:39 UTC, damirovna commented on main-server/src/main/java/ru/practicum/ewm/user/model/User.java
> +    @Column(length = 128, unique = true)
[Нужно исправить]

128 слишком мало для адреса

2022-10-07 10:57 UTC, marussiakuz commented on main-server/src/main/java/ru/practicum/ewm/event/model/dto/EventFullOutDto.java
> +public class EventFullOutDto implements EventOutDto {
Сделала EventOutDto абстрактным классом (ранее был интерфейсом) c основными полями, которые были у EventShortOutDto, EventFullOutDto и EventShortOutDto наследуются от него. Не стала делать наследование EventFull от EventShort на тот случай если в Short-версии возникнет потребность добавить поле, которое не должно быть у Full-версии

2022-10-07 10:57 UTC, marussiakuz commented on main-server/src/main/resources/schema.sql
> +    category_name VARCHAR UNIQUE NOT NULL,
указала размер

2022-10-07 10:59 UTC, marussiakuz commented on main-server/src/main/java/ru/practicum/ewm/user/model/User.java
> +    @Column(length = 128, unique = true)
тут имя пользователя (не адрес), но на всякий случай сделала 256 если имя нестандартное)

2022-10-10 13:04 UTC, merged